name: CI -> Deploy to My website
on:
   push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Here is the deployment action
      - name: Upload from dist via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with: 
          server: ${{ secrets.SERVER }}
          user:  ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          local_dir: "./public"
          #remote_dir: costs
          delete: "true"